"""add admin_status

Revision ID: 72dcb1eaaf1e
Revises: c8a285597f65
Create Date: 2022-12-03 14:27:10.192589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dcb1eaaf1e'
down_revision = 'c8a285597f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_admin', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_db', schema=None) as batch_op:
        batch_op.drop_column('status_admin')

    # ### end Alembic commands ###
